x <- read.delim("household_power_consumption.txt", sep= ";", header=FALSE, na.strings= "?", skip= 66600, n= 3050)
x<-as.data.frame(x)
data<-subset(x, as.Date(V1) == "01/02/2007"| as.Date(V1) == "02/02/2007")
Date<-as.character(data$V1)
Time<-as.character(data$V2)
y<-paste(Date,Time)
d <- strptime(y,"%d/%m/%Y %H:%M:%S")
plot(d, data$V3, ylab= "Global Active Power (kilowatts)", xlab=" ", type= "l")
dev.copy(png, file="plot2.png",width=480,height=480)
dev.off()
