x <- read.delim("household_power_consumption.txt", sep= ";", header=FALSE, na.strings= "?", skip= 66600, n= 3050)
x<-as.data.frame(x)
data<-subset(x, as.Date(V1) == "01/02/2007"| as.Date(V1) == "02/02/2007")
Date<-as.character(data$V1)
Time<-as.character(data$V2)
y<-paste(Date,Time)
d <- strptime(y,"%d/%m/%Y %H:%M:%S")
png(file="plot4.png", width=480,height=480)
par(mfrow=c(2,2))
plot(d, data$V3, ylab= "Global Active Power (kilowatts)", xlab=" ", type= "l")
plot(d, data$V5, ylab= "Voltage", xlab="datetime", type= "l")
plot(d, data$V7, ylab= "Energy sub metering", xlab=" ", type= "n")
lines(d, data$V7,col="black")
lines(d, data$V8,col="red1")
lines(d, data$V9,col="blue1")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty="n", cex=1, yjust=0, xjust=0, y.intersp=1, lwd=1, lty=1, pch=c(NA, NA, NA), col=c("black", "red1", "blue1"))
plot(d, data$V4, ylab= "Global_Reactive_Power", xlab="datetime", type= "l")
dev.off()
